[package]
name = "nlsn-delaunay-refine"
version = "0.1.0"
authors = ["nelson kenzo tamashiro <nelsonkenzotamashiro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.20"
